name: CI
on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, labeled, synchronize]
    branches:
      - main
jobs:
  docker-image:
    uses: ./.github/workflows/docker.yml
  linux:
    runs-on: ubuntu-latest
    needs: [docker-image]
    container:
      image: ghcr.io/michael-barrow-llnl/pylibROM/pylibROM_env:latest
      options: --user 1001 --privileged
      volumes:
        - /mnt:/mnt
    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      - name: Check out pylibROM
        uses: actions/checkout@v1
        with:
          submodules: 'true'
      - name: build
        run: |
            cd extern/libROM
            ./scripts/compile.sh -m
            echo built pylibROM
            cd ../../
            mkdir build
            cd build
            cmake ..
            make
            echo built pylibROM
      - name: test
        run: |
            cd tests
            echo run pyVector unit test
            pytest test_pyVector.py
            echo run pyMatrix unit test
            pytest test_pyMatrix.py
